algoritmo "Calcular a area de um retangulo"
// Função :
// Autor :
// Data : 26/03/2019
// Seção de Declarações 
var
a,b,resp :real
inicio
// Seção de Comandos 
escreval ("*******************************")
escreval ("calcular a area de um retangulo")
escreval ("*******************************")
escreval ("")
escreval ("Digite o valor da base")
leia (a)
escreval ("Digite o valor da altura")
leia (b)
resp <- exp (a*b,2)
escreval ("A area deste retângulo," ,resp)

fimalgoritmo
